sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t jhoog1992/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true jhoog1992/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-eu-central-1-939102219448"
  bucket_path: "docker-react"
  on:
    - branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY